// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjeEX25xToBpeh4wwnhbQHJ3zZf37a5M',
    appId: '1:1088213596238:android:6d03e3f3e28cb1aa30ab1f',
    messagingSenderId: '1088213596238',
    projectId: 'schedula-543b1',
    storageBucket: 'schedula-543b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShp6QYkUrCy_wOU7hA3uz7kTT57DshW4',
    appId: '1:1088213596238:ios:92c229b071870c8f30ab1f',
    messagingSenderId: '1088213596238',
    projectId: 'schedula-543b1',
    storageBucket: 'schedula-543b1.firebasestorage.app',
    androidClientId: '1088213596238-i4mg270gbifegnj3s9dndj5lvepof6su.apps.googleusercontent.com',
    iosClientId: '1088213596238-sfi3dijr70b26rp0fu7579rl3mfr64q9.apps.googleusercontent.com',
    iosBundleId: 'com.exe.schedula',
  );
}
