import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart'; // Generated by build_runner

// Service locator instance
final getIt = GetIt.instance;

/// Configures the dependency injection container.
///
/// This function is annotated with [@InjectableInit], which triggers the
/// code generation process via `build_runner`. The generated code in
/// `injection.config.dart` will contain all the necessary dependency
/// registration logic based on the annotations used throughout the app
/// (e.g., @injectable, @singleton, @lazySingleton).
@InjectableInit()
Future<void> configureDependencies() async => getIt.init();